services:
    wedding-go-service: # go service
        container_name: wedding-go-service
        image: alpine:3.21.3
        restart: "no"
        depends_on: # wait for mysql to start before this container
            - wedding-mysql-service
        volumes:
            - ./docker-volumes/main-service-files:/app
        ports:
            - "${WEDDING_SERVICE_HTTP_PORT}:${WEDDING_SERVICE_HTTP_PORT}"
            - "${WEDDING_SERVICE_HTTPS_PORT}:${WEDDING_SERVICE_HTTPS_PORT}"
        #env_file:
        #    - .env
        environment:
            - GOOS=linux
            - GOARCH=amd64
            - MODE=docker-dev # TODO: fix it so docker puts the mode in, instead of docker compose env we do now. (this will get overwritten, which is a problem)
        working_dir: /app
        command: ./${APP_NAME} -frontend=./webserver/website/frontend/out # development frontend mode
        networks:
            - wedding-network

    wedding-mysql-service: # mysql
        container_name:  wedding-mysql-service
        image: mysql:8.4.5
        restart: "no"
        volumes:
            - ./docker-volumes/mysql-data:/var/lib/mysql
        env_file:
            - .env
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_SERVICE_ROOT_PASSWORD}"
        ports:
            - "${MYSQL_SERVICE_HTTP_PORT}:${MYSQL_SERVICE_HTTP_PORT}"
        networks:
            - wedding-network
    wedding-prometheus:
        container_name: wedding-prometheus
        image: prom/prometheus:latest
        restart: "no"
        ports:
            - "9090:9090"
        networks:
            - wedding-network
    wedding-grafana:
        container_name: wedding-grafana
        image: grafana/grafana:latest
        restart: "no"
        ports:
            - "3000:3000"
        networks:
            - wedding-network
networks:
    wedding-network: