services:
    wedding-go-service: # go service
        container_name: wedding-go-service
        image: alpine:3.21.3
        restart: no
        depends_on: # wait for mysql to start before this container
            - wedding-mysql-service
        volumes:
            - ./docker-volumes/main-service-files:/app
        ports:
            - "80:${WEDDING_SERVICE_HTTP_PORT}"
            - "443:${WEDDING_SERVICE_HTTPS_PORT}"
        env_file:
            - .env
        working_dir: /app
        command: ./${APP_NAME}
        networks:
            - wedding-network

    wedding-mysql-service: # mysql
        container_name:  wedding-mysql-service
        image: mysql:8.4.5
        restart: no
        volumes:
            - ./docker-volumes/mysql-data:/var/lib/mysql
        ports:
            - "3306:${MYSQL_SERVICE_HTTP_PORT}"
        env_file:
            - .env
        networks:
            - wedding-network
    wedding-prometheus:
        container_name: wedding-prometheus
        image: prom/prometheus:latest
        restart: no
        ports:
            - "9090:9090"
        networks:
            - wedding-network
    wedding-grafana:
        container_name: wedding-grafana
        image: grafana/grafana:latest
        restart: no
        ports:
            - "3000:3000"
        networks:
            - wedding-network
networks:
    wedding-network: