global:
  scrape_interval: 5s  # How often Prometheus scrapes targets

scrape_configs:
  - job_name: 'wedding-go-service'
    static_configs:
      - targets: ['https://wedding-go-service:8443']  # Go service's address and port

  - job_name: 'wedding-mysql-service'
    static_configs:
      - targets: ['http://wedding-mysql-service:3306']  # MySQL service monitoring

  - job_name: 'wedding-promtail'
    static_configs:
      - targets: ['http://wedding-promtail:3100']  # Loki endpoint for log scraping
